WIDTH = 1440
HEIGHT = 720
GRID_SIZE = 6
CELL_COUNT = GRID_SIZE ** 2
MINES_COUNT = CELL_COUNT // 4

GAME_BG = '#A9A9A9'
CELL_DEFAULT_BG = '#FFFFF0'
CELL_FLAG_BG = '#FFA500'
CELL_HOVER_BG = "#D3D3D3"
CELL_MINE_BG = "#FF4C4C"